db:
  username: ${username.value:postgres}
  password: pass
  driver: PostgresDriver
  url: postgres5432
  hosts: localhost,127.0.0.1
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - second
    - third

#spring.profiles.active:qa